### ISSUE TITLE
Hi, 您好

### ISSUE THREAD

**Issue by zjhch123** [hzzhangjiahao/hzzhangjiahao.github.io#1]
您好，很高兴认识您。
我们很有缘。同为zjh，同为zhangjiahao，同样喜欢钻研技术，也同样是猪场员工。
希望我们都能在技术的道路上越走越远。

再次，认识您很高兴。
zhangjiahao

**Comment by hzzhangjiahao** [comment]
您好，有缘人。
虽然我只在猪厂短暂实习过，不过猪厂的文化直到现在还在影响着我，猪厂是个好地方，祝好！

zhangjiahao
